export enum CommentServiceError {
  POST_NOT_FOUND = 1,
  USER_NOT_FOUND = 2,
  USER_ID_REQUIRED = 3,
  COMMENT_NOT_FOUND = 4,
  COMMENT_ACCESS_DENIED = 5,
  COMMENT_NOT_UPDATED = 6,
  COMMENT_NOT_DELETED = 7,
  COMMENT_NOT_CREATED = 8,
}
