export enum QuizResultError {
  QUIZ_QUESTION_NOT_FOUND = 1,
  QUIZ_QUESTION_NOT_DELETED = 2,

  QUIZ_GAME_NO_FOUND = 3,
  QUIZ_GAME_NO_PERMISSION = 4,

  QUIZ_CONNECTION_ERROR = 5,
  QUIZ_CREATION_GAME_ERROR = 6,
}
