export enum AuthServiceError {
  AUTH_USER_NO_FOUND = 1,
  AUTH_USER_NOT_CONFIRMED = 2,
  AUTH_USER_PASS_NOT_VERIFIED = 3,
  AUTH_SESSION_NOT_EXIST = 4,
  AUTH_SESSION_NOT_UPDATED = 5,
  AUTH_REG_CONFIRMATION_INVALID = 6,
  AUTH_PASS_CONFIRMATION_INVALID = 7,
  AUTH_CODE_ALREADY_CONFIRMED = 8,
}
